export const START_CHAPEL_LOAD = 'START_CHAPEL_LOAD';
export const RECEIVE_CHAPEL_LOAD = "RECEIVE_CHAPEL_LOAD";

export const START_EVENTS_LOAD = 'START_EVENTS_LOAD';
export const RECEIVE_EVENTS_LOAD = "RECEIVE_EVENTS_LOAD";

export const RECEIVE_DINING_LOAD = "RECEIVE_DINING_LOAD";
export const START_DINING_LOAD = "START_DINING_LOAD";

export const RECIEVE_NEWS_LOAD = "RECIEVE_NEWS_LOAD";
export const START_NEWS_LOAD = "START_NEWS_LOAD";
