export const START_CHAPEL_LOAD = 'START_CHAPEL_LOAD';
export const RECIEVE_CHAPEL_LOAD = "RECIEVE_CHAPEL_LOAD";

export const START_EVENT_LOAD = 'START_EVENT_LOAD';
export const RECEIVE_EVENT_LOAD = "RECEIVE_EVENT_LOAD";